#pragma once
#include "scheduler/scheduler.h"

#define CONFIG_TASK_SYSTEM_PERIOD_HZ 5
#define CONFIG_TASK_READ_ANALOG_SENSORS_HZ 2

#define CONFIG_TASK_PID_HZ 200
#define CONFIG_TASK_READ_DEPTH_SENSOR_HZ 30

#define CONFIG_TASK_COMM_HANDLER_HZ 5

#define CONFIG_TASK_AUTOMATIONS_HZ 10

#define CONFIG_TASK_DIRECT_MOTORS_CTRL_HZ 10

#define CONFIG_TASK_HEART_BEAT_HZ 2

#define CONFIG_TASK_TELEMETRY_HZ 2
#define CONFIG_TASK_TELEMETRY_PRIORITY TASK_PRIORITY_LOW