#pragma once

#define TASK_SYSTEM_PERIOD_HZ 5
#define TASK_READ_ANALOG_SENSORS_HZ 2
#define TASK_TELEMETRY_DEBUG_HZ 2
#define TASK_PID_HZ 200
#define TASK_READ_DEPTH_SENSOR_HZ 30

#define TASK_COMM_HANDLER_HZ 10

#define TASK_AUTOMATIONS_HZ 10

#define TASK_DIRECT_MOTORS_CTRL_HZ 10

#define TASK_HEART_BEAT_HZ 2